---
title: "305 Lecture 4.3 - More Examples of Truth Trees"
author: "Brian Weatherson"
mainfont: SF Pro Rounded
output:
  beamer_presentation:
    md_extensions: +link_attributes+fenced_divs
    keep_tex: yes
    latex_engine: xelatex
    includes:
      in_header: 305-beamer-header.tex
mathfont: STIX Two Math
mainfontoptions: BoldFont = SF Pro Rounded Semibold
---

## Plan

This lecture goes over some more examples of truth trees.

## Associated Reading

Boxes and Diamonds, section 2.5.

## Not Many Slides

- This lecture is different to most.
- I'm not going to be talking over the slides.
- Instead, I've posted 8 different videos going over 8 examples.

## Examples

a. $\neg A \vee \neg B \vdash \neg (A \vee B)$
b. $\neg A \wedge \neg B \vdash \neg (A \vee B)$
c. $\neg (A \wedge B) \vdash \neg (A \vee B)$
d. $\neg (A \vee B) \vdash \neg (A \wedge B)$
e. $\neg A \vee B, A \vdash B$
f. $\neg A \vee B \vdash A \rightarrow B$
g. $A \rightarrow (B \rightarrow C) \vdash (A \vee B) \rightarrow C$
h. $A \rightarrow (B \rightarrow C) \vdash (A \wedge B) \rightarrow C$

## Other Examples for You (or discussion)

1. $A \rightarrow C \vdash (A \vee B) \rightarrow C$
2. $A \rightarrow C \vdash (A \wedge B) \rightarrow C$
3. $(A \rightarrow C) \wedge (B \rightarrow C) \vdash (A \wedge B) \rightarrow C$
4. $(A \rightarrow C) \wedge (B \rightarrow C) \vdash (A \vee B) \rightarrow C$
5. $(A \rightarrow C) \vee (B \rightarrow C) \vdash (A \wedge B) \rightarrow C$
6. $(A \rightarrow C) \vee (B \rightarrow C) \vdash (A \vee B) \rightarrow C$
7. $(A \rightarrow (B \rightarrow C)) \rightarrow (B \rightarrow (A \rightarrow C))$
8. $A \rightarrow ((A \rightarrow B) \rightarrow B))$
9. $(A \rightarrow B) \rightarrow (A \rightarrow B)$
10. $(A \rightarrow (B \rightarrow C)) \rightarrow ((A \rightarrow B) \rightarrow (A \rightarrow C))$

## For Next Time

We will start a unit on part IV of forall x, on natural deduction.