---
title: "305 Lecture 12.1 - Modal Tableau"
author: "Brian Weatherson"
mainfont: SF Pro Rounded
output:
  beamer_presentation:
    md_extensions: +link_attributes+fenced_divs
    keep_tex: yes
    latex_engine: xelatex
    includes:
      in_header: 305-beamer-header.tex
mathfont: STIX Two Math
mainfontoptions: BoldFont = SF Pro Rounded Semibold
---

## Plan

- To introduce tableau for proving things in modal logic.

## Associated Reading

- Boxes and Diamonds, section 5.1

## Modal Tableau

One big difference:

- On each line, we include reference to a world.
- The line says that a particular proposition is true or false _at a world_.
- The tableau only close if the tableau says the same proposition is both true and false _at the same world_.

## Referring to Worlds

We refer to a world with a string of numbers, such as 1.2.1.3.

- The string tells you something (but not everything) about R relations.
- World $x$ can always access world $x.y$.
- So there is an R-relation from 1.2.1 to 1.2.1.3, and indeed to 1.2.1.$x$ for any $x$.
- These don't exhaust the R-relations; perhaps there is also an R-relation from 1.2.1.3 back to 1.2.1.
- But the relation from $x$ to $x.y$ is guaranteed.
- Note that worlds can be picked out by multiple strings - we do not assume that 1.1 and 1.2 are different, though we don't assume they are the same either.

## Rules

The rules for the old connectives stay as they are.

- The only difference is that you have to note which world you are in.
- So if you have that $A \wedge B$ is true in 1.4.7, then you have to write down that $A$ is true in 1.4.7, and that $B$ is true in 1.4.7.
- And if $A \vee B$ is true in 1.6.8 you have to have two branches, one where $A$ is true in 1.6.8, and the other where $B$ is true in 1.6.8.
- But otherwise things are as they were before.

## Rules for $\Box$

If $\Box A$ is true at $x$, then for any $x.y$ that is already on the tree, we can infer that $A$ is true at $x.y$.

- Note: If there is no $x.y$ on the tree, we can't assume that there is one.
- $\Box A$ can be true at a world because that world can't access any other world.

## Rules for $\Box$ (cont)

If $\Box A$ is false at $x$, then we have to add a **new** $x.y$, and make $A$ false at $x.y$.

- It is very important that $x.y$ be new.
- We know that $A$ is false at some accessible world, but we don't know which one.
- For any given world, $A$ might be true there, as long as it is false somewhere.
- That's why we use a new number.
- Remember that it might be that multiple strings refer to the same world.

## Rules for $\Diamond$

If $\Diamond A$ is true at $x$, then we have to add a **new** $x.y$, and make $A$ true at $x.y$.

- It is very important that $x.y$ be new.
- We know that $A$ is true at some accessible world, but we don't know which one.
- For any given world, $A$ might be false there, as long as it is false somewhere.
- That's why we use a new number.
- Remember that it might be that multiple strings refer to the same world.

## Rules for $\Diamond$ (cont)

If $\Diamond A$ is false at $x$, then for any $x.y$ that is already on the tree, we can infer that $A$ is false at $x.y$.

- Note: If there is no $x.y$ on the tree, we can't assume that there is one.
- $\Diamond A$ can be false at a world because that world can't access any other world.


## $(\Box A \wedge \Box B) \rightarrow \Box (A \wedge B)$

  \begin{oltableau}
    [\pFmla{\False}{(\Box\formula{A} \land \Box\formula{B}) \lif
        \Box (\formula{A} \land \formula{B})}{1},
      just =\TAss
      [\pFmla{\True}{\Box\formula{A} \land \Box\formula{B}}{1},
        just = {\TRule{\False}{\lif}[1]}
        [\pFmla{\False}{\Box(\formula{A} \land \formula{B})}{1},
          just = {\TRule{\False}{\lif}[1]}
          [\pFmla{\True}{\Box\formula{A}}{1},
            just = {\TRule{\True}{\land}[2]}
            [\pFmla{\True}{\Box\formula{B}}{1},
              just = {\TRule{\True}{\land}[2]}
              [\pFmla{\False}{\formula{A} \land \formula{B}}{1.1},
                just = {\TRule{\False}{\Box}[3]}
                [\pFmla{\False}{\formula{A}}{1.1}, 
                  just = {\TRule{\False}{\land}[6]}
                  [\pFmla{\True}{\formula{A}}{1.1},
                    just= {\TRule{\True}{\Box}[4]}, close]]
                [\pFmla{\False}{\formula{B}}{1.1}, 
                  just = {\TRule{\False}{\land}[6]}
                  [\pFmla{\True}{\formula{B}}{1.1},
                    just= {\TRule{\True}{\Box}[5]}, close]]
              ]
            ]
          ]
        ]
      ]
    ]
  \end{oltableau}


## $\Diamond (A \vee B) \rightarrow (\Diamond A \vee \Diamond B)$

\begin{oltableau}
    [\pFmla{\False}{\Diamond(\formula{A} \lor \formula{B}) \lif
        (\Diamond \formula{A} \lor \Diamond \formula{B})}{1},
      just =\TAss
      [\pFmla{\True}{\Diamond(\formula{A} \lor \formula{B})}{1},
        just = {\TRule{\False}{\lif}[1]}
        [\pFmla{\False}{\Diamond\formula{A} \lor \Diamond\formula{B}}{1},
          just = {\TRule{\False}{\lif}[1]}
          [\pFmla{\False}{\Diamond\formula{A}}{1},
            just = {\TRule{\False}{\lor}[3]}
            [\pFmla{\False}{\Diamond\formula{B}}{1},
              just = {\TRule{\False}{\lor}[3]}
              [\pFmla{\True}{\formula{A} \lor \formula{B}}{1.1},
                just = {\TRule{\True}{\Diamond}[2]},
                [\pFmla{\True}{\formula{A}}{1.1}, 
                  just = {\TRule{\True}{\lor}[6]}
                  [\pFmla{\False}{\formula{A}}{1.1},
                    just= {\TRule{\False}{\Diamond}[4]}, close]]
                [\pFmla{\True}{\formula{B}}{1.1}, 
                  just = {\TRule{\True}{\lor}[6]}
                  [\pFmla{\False}{\formula{B}}{1.1},
                    just= {\TRule{\False}{\Diamond}[5]}, close]]
              ]
            ]
          ]
        ]
      ]
    ]
  \end{oltableau}

## For Next Time

We'll look at how to extend this approach to other logics.