---
title: $(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)$ (in K)
author: Build a Tableau
date: To Check Whether it is Valid
mainfont: SF Pro Rounded
mainfontoptions:
  - BoldFont = SF Pro Rounded Semibold
mathfont: STIX Two Math
output: 
  beamer_presentation:
    md_extensions: +link_attributes
    keep_tex: true
    latex_engine: xelatex
    includes:
      in_header: 305-beamer-header.tex
---

## Hypothesis

$(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)$ is a theorem of K.

- So we can use the base modal rules.

## $(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)$

\begin{oltableau}
[\pFmla{\False}{(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)}{1}, just = \TAss,
]
\end{oltableau}

\bigskip

Start with it being false at 1.

## $(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)$

\begin{oltableau}
[\pFmla{\False}{(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)}{1}, checked, just = \TAss,
  [\pFmla{\True}{\Diamond A \wedge \Diamond B}{1}, just = {\TRule{\False}{\rightarrow}[1]},
    [\pFmla{\False}{\Diamond (A \wedge B)}{1}, just = {\TRule{\False}{\rightarrow}[1]}
    ]
  ]
]
\end{oltableau}

\bigskip

True antecedent, false consequent.

## $(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)$

\begin{oltableau}
[\pFmla{\False}{(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)}{1}, checked, just = \TAss,
  [\pFmla{\True}{\Diamond A \wedge \Diamond B}{1},  checked, just = {\TRule{\False}{\rightarrow}[1]},
    [\pFmla{\False}{\Diamond (A \wedge B)}{1},just = {\TRule{\False}{\rightarrow}[1]}
      [\pFmla{\True}{\Diamond A}{1}, just = {\TRule{\True}{\wedge}[2]}
        [\pFmla{\True}{\Diamond B}{1}, just = {\TRule{\True}{\wedge}[2]}
        ]
      ]
    ]
  ]
]
\end{oltableau}

\bigskip

Break up the and.

## $(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)$

\begin{oltableau}
[\pFmla{\False}{(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)}{1}, checked, just = \TAss,
  [\pFmla{\True}{\Diamond A \wedge \Diamond B}{1}, checked,just = {\TRule{\False}{\rightarrow}[1]},
    [\pFmla{\False}{\Diamond (A \wedge B)}{1},  just = {\TRule{\False}{\rightarrow}[1]}
      [\pFmla{\True}{\Diamond A}{1}, checked, just = {\TRule{\True}{\wedge}[2]}
        [\pFmla{\True}{\Diamond B}{1}, just = {\TRule{\True}{\wedge}[2]}
          [\pFmla{\True}{A}{1.1}, just = {\TRule{\True}{\Diamond}[4]}
          ]
        ]
      ]
    ]
  ]
]
\end{oltableau}

\bigskip

Make $\Diamond A$ true.

## $(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)$

\begin{oltableau}
[\pFmla{\False}{(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)}{1}, checked, just = \TAss,
  [\pFmla{\True}{\Diamond A \wedge \Diamond B}{1}, checked, just = {\TRule{\False}{\rightarrow}[1]},
    [\pFmla{\False}{\Diamond (A \wedge B)}{1},  just = {\TRule{\False}{\rightarrow}[1]}
      [\pFmla{\True}{\Diamond A}{1}, checked, just = {\TRule{\True}{\wedge}[2]}
        [\pFmla{\True}{\Diamond B}{1}, just = {\TRule{\True}{\wedge}[2]}
          [\pFmla{\True}{A}{1.1}, just = {\TRule{\True}{\Diamond}[4]}
            [\pFmla{\False}{A \wedge B}{1.1}, just = {\TRule{\False}{\Diamond}[3]}
            ]
          ]
        ]
      ]
    ]
  ]
]
\end{oltableau}

\bigskip

Since $A \wedge B$ is false everywhere accessible from 1, it is false at 1.1.

## $(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)$

\begin{oltableau}
[\pFmla{\False}{(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)}{1}, checked, just = \TAss,
  [\pFmla{\True}{\Diamond A \wedge \Diamond B}{1}, checked, just = {\TRule{\False}{\rightarrow}[1]},
    [\pFmla{\False}{\Diamond (A \wedge B)}{1},  just = {\TRule{\False}{\rightarrow}[1]}
      [\pFmla{\True}{\Diamond A}{1}, checked, just = {\TRule{\True}{\wedge}[2]}
        [\pFmla{\True}{\Diamond B}{1}, just = {\TRule{\True}{\wedge}[2]}
          [\pFmla{\True}{A}{1.1}, just = {\TRule{\True}{\Diamond}[4]}
            [\pFmla{\False}{A \wedge B}{1.1}, checked, just = {\TRule{\False}{\Diamond}[3]}
              [\pFmla{\False}{A}{1.1}, just = {\TRule{\False}{\wedge}[7]}, close]
              [\pFmla{\False}{B}{1.1}, just = {\TRule{\False}{\wedge}[7]}
              ]
            ]
          ]
        ]
      ]
    ]
  ]
]
\end{oltableau}

\bigskip

Two ways for $A \wedge B$ to fail; only one is possible.

## $(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)$

\begin{oltableau}
[\pFmla{\False}{(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)}{1}, checked, just = \TAss,
  [\pFmla{\True}{\Diamond A \wedge \Diamond B}{1}, checked, just = {\TRule{\False}{\rightarrow}[1]},
    [\pFmla{\False}{\Diamond (A \wedge B)}{1},  just = {\TRule{\False}{\rightarrow}[1]}
      [\pFmla{\True}{\Diamond A}{1}, checked, just = {\TRule{\True}{\wedge}[2]}
        [\pFmla{\True}{\Diamond B}{1}, checked, just = {\TRule{\True}{\wedge}[2]}
          [\pFmla{\True}{A}{1.1}, just = {\TRule{\True}{\Diamond}[4]}
            [\pFmla{\False}{A \wedge B}{1.1}, checked, just = {\TRule{\False}{\Diamond}[3]}
              [\pFmla{\False}{A}{1.1}, just = {\TRule{\False}{\wedge}[7]}, close]
              [\pFmla{\False}{B}{1.1}, just = {\TRule{\False}{\wedge}[7]}
                  [\pFmla{\True}{B}{1.2}, just = {\TRule{\True}{\Diamond}[5]}
                  ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
]
\end{oltableau}

$B$ has to be possible, so we'll say it is possible at 1.2 - using a name we haven't already used.

## $(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)$

\begin{oltableau}
[\pFmla{\False}{(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)}{1}, checked, just = \TAss,
  [\pFmla{\True}{\Diamond A \wedge \Diamond B}{1}, checked, just = {\TRule{\False}{\rightarrow}[1]},
    [\pFmla{\False}{\Diamond (A \wedge B)}{1},  just = {\TRule{\False}{\rightarrow}[1]}
      [\pFmla{\True}{\Diamond A}{1}, checked, just = {\TRule{\True}{\wedge}[2]}
        [\pFmla{\True}{\Diamond B}{1}, checked, just = {\TRule{\True}{\wedge}[2]}
          [\pFmla{\True}{A}{1.1}, just = {\TRule{\True}{\Diamond}[4]}
            [\pFmla{\False}{A \wedge B}{1.1}, checked, just = {\TRule{\False}{\Diamond}[3]}
              [\pFmla{\False}{A}{1.1}, just = {\TRule{\False}{\wedge}[7]}, close]
              [\pFmla{\False}{B}{1.1}, just = {\TRule{\False}{\wedge}[7]}
                  [\pFmla{\True}{B}{1.2}, just = {\TRule{\True}{\Diamond}[5]}
                    [\pFmla{\False}{A \wedge B}{1.2}, just = {\TRule{\False}{\Diamond}[3]}
                    ]
                  ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
]
\end{oltableau}

$A \wedge B$ is still impossible.

## $(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)$

\begin{footnotesize}
\begin{oltableau}
[\pFmla{\False}{(\Diamond A \wedge \Diamond B) \rightarrow \Diamond (A \wedge B)}{1}, checked, just = \TAss,
  [\pFmla{\True}{\Diamond A \wedge \Diamond B}{1}, checked, just = {\TRule{\False}{\rightarrow}[1]},
    [\pFmla{\False}{\Diamond (A \wedge B)}{1}, just = {\TRule{\False}{\rightarrow}[1]}
      [\pFmla{\True}{\Diamond A}{1}, checked, just = {\TRule{\True}{\wedge}[2]}
        [\pFmla{\True}{\Diamond B}{1}, checked, just = {\TRule{\True}{\wedge}[2]}
          [\pFmla{\True}{A}{1.1}, just = {\TRule{\True}{\Diamond}[4]}
            [\pFmla{\False}{A \wedge B}{1.1}, checked, just = {\TRule{\False}{\Diamond}[3]}
              [\pFmla{\False}{A}{1.1}, just = {\TRule{\False}{\wedge}[7]}, close]
              [\pFmla{\False}{B}{1.1}, just = {\TRule{\False}{\wedge}[7]}
                  [\pFmla{\True}{B}{1.2}, just = {\TRule{\True}{\Diamond}[5]}
                    [\pFmla{\False}{A \wedge B}{1.2}, checked, just = {\TRule{\False}{\Diamond}[3]}
                      [\pFmla{\False}{A}{1.2}, just = {\TRule{\False}{\wedge}[7]}]
                      [\pFmla{\False}{B}{1.2}, just = {\TRule{\False}{\wedge}[7]}, close]
                    ]
                  ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
]
\end{oltableau}
And we're done. All the rules have been applied - though you really need to check this - and the middle branch does not close.
\end{footnotesize}

## A Model

When the tableau doesn't close, you should be able to build a model where the sentence is false at $w_1$.

In fact, you should be able to read it off the tree.

## A Model 

- Three worlds, $w_1, w_{1.1}, w_{1.2}$.
- The only accessibility relations are $w_1Rw_{1.1}$ and $w_1Rw_{1.2}$.
- In general, the accessibility relations are the ones required by the restrictions (but there are none here), plus the ones required by the numbering, i.e., $w_xRw_{x.y}$.
- $A$ is true at $w_{1.1}$ and false at $w_{1.2}$.
- $B$ is true at $w_{1.2}$ and false at $w_{1.1}$.
- It doesn't matter what atomics are true at $w_1$.
- But both $\Diamond A$ and $\Diamond B$ will be true at $w_1$, while $\Diamond (A \wedge B)$ is false there.

