---
title: "305 Lecture 14.2 - The Logic Of Counterfactuals"
author: "Brian Weatherson"
mainfont: SF Pro Rounded
output:
  beamer_presentation:
    md_extensions: +link_attributes+fenced_divs
    keep_tex: yes
    latex_engine: xelatex
    includes:
      in_header: 305-beamer-header.tex
mathfont: STIX Two Math
mainfontoptions: BoldFont = SF Pro Rounded Semibold
---

## Plan

- To discuss some features of the logic of counterfactual conditionals.

## Associated Reading

- _Boxes and Diamonds_, chapter 7.

## Antecedent Strengthening

This fails on the minimal change semantics.

## Antecedent Strengthening

What is it?

1. $A \boxright B$.
2. so, $(A \wedge C) \boxright B$

## Antecedent Strengthening

Why does it fail? Because this is possible.

- The nearest $A$-world is 10 units away, and at it, $B$ is true, but $C$ is false.
- The nearest $A \wedge C$-world is 100 units away, and at it, $C$ is true (of course), but $B$ is false.

## Antecedent Strengthening

Put in less technical terms, it fails when these things happen at once.

> - In all normal worlds, when $A$ is true, $B$ is true and $C$ is false.
> - So there are no normal worlds where $A \wedge C$.
> - But in the $A \wedge C$-worlds that are only a bit abnormal, $B$ is false.

## Skiing Example

Here are some things we might imagine are true in all normal possibilities.

- When it snows, it snows a normal amount - it isn't a blizzard.
- When it snows, Jack goes skiing.
- Jack has no disposition to want to ski in a blizzard. \pause

So in the most normal blizzard world, Jack does not go skiing. And we have both of the following.

- If it had snowed, Jack would have gone skiing.
- If there had been snow and a blizzard, Jack would not have gone skiing.

## Transitivity (or Conditional Syllogism)

This argument seems initially compelling for any interpretation of 'if'.

1. If $A, B$.
2. If $B, C$.
3. So if $A, C$.

## Transitivity for Subjunctives

On the nearest possible world, or minimal change, semantics, this will fail for subjunctive conditionals.

- Imagine there is no nearby world where $A$.
- The nearest $A$ worlds (which in these cases will be quite distant) are worlds where $B$ is true and $C$ is false.
- There are nearby, normal $B$ worlds, and they are all worlds where $C$ is true.

## Real Life Example

1. If there had been a hurricane and a blizzard on Presidents' Day Weekend, it would have snowed on Presidents' Day Weekend. \pause 
2. If it had snowed on Presidents' Day Weekend, Jack would have gone skiing on Presidents' Day Weekend. \pause 
3. So if there had been a hurricane and a blizzard on Presidents' Day Weekend, Jack would have gone skiing on Presidents' Day Weekend.

## Link To Antecedent Strengthening

1. If I had crashed my car last week and won the lottery on the weekend, I'd have crashed my car last week. \pause 
2. If I had crashed my car last week, I'd now have less money than actually do. \pause 
3. So if I had crashed my car last week and won the lottery on the weekend, I'd now have less money than actually do.

## Recipe Here

Assume that you have _If A, C_, but not _If A and B, C_.

1. If $A$ and $B$, $A$.
2. If $A, C$.
3. So, If $A$ and $B$, $C$.

That should have true premises and a false conclusion.

## But Wait

But don't we reason this way all the time.

1. If there had been a major earthquake in Ann Arbor last weekend, several buildings in Ann Arbor would have been destroyed. \pause 
2. If several buildings in Ann Arbor were destroyed, I would have been very upset. \pause 
3. So if there had been a major earthquake in Ann Arbor on the weekend, I would have been very upset.

The point is not that 1-3 look true here, it's that reasoning from 1 and 2 to 3 looks like good, ordinary, everyday reasoning.

## Modified Transitivity

This argument form is valid on the minimal change semantics.

1. If $A, B$
2. If $A \wedge B, C$
3. So, if $A, C$

## Proof Of Modified Transitivity

- Let $d$ be the distance of the nearest $A$ world.
- By premise 1, all of those nearest $A$ worlds, which are distance $d$ away, are $B$ worlds. \pause 
- So they are also the nearest $A \wedge B$ worlds. (There can't be any closer, because then they would be closer $A$ worlds.) \pause 
- By premise 2 then, all these $A \wedge B$ worlds distance $d$ away are also $C$ worlds.
- So all the $A$ worlds distance $d$ away are $C$ worlds. \pause 
- So, if $A, C$.

## Explanation

Lewis suggested that was what was really going on when we use transitivity arguments in everyday life.

- The middle premise is really _If A and B, C_, not just _If B, C_.
- Is this plausible? I don't know.

## That's All!

Next class will just be about revision before the final. Thanks for staying to the end!