---
title: "Assignment Week 9"
output:
  pdf_document:
    toc: false
    df_print: kable
    keep_tex: yes
    latex_engine: xelatex
    md_extensions: +fancy_lists
    extra_dependencies: ["gensymb", "nicefrac", "caption", "mathastext"]
    fig_caption: no
fontsize: 11pt
mainfont: SF Pro Text Light
mainfontoptions: "Scale=MatchLowercase"
geometry: margin=1.2in
linestretch: 1.1
author: Philosophy 305
date: Due March 19, 2021
---

## Question 1

What is the expected monetary value of playing a slot machine that costs $100 to play, and has a 1/25 chance of paying out $500? (The rest of the time it pays nothing.)

 
## Question 2

Suppose a slot machine pays off $25 a fiftieth of the time and costs a $1 to play, and a video poker machine pays off $10 a twentieth of the time and costs $2 to play. Which machine is the better bet in terms of expected monetary value?

 
## Question 3

Youʼre considering downloading a new game for your phone. The game costs $0.99. But as a promotion, the first 50,000 downloaders are being entered in a fair lottery with a $10,000 cash prize. If you know youʼll be one of the first 50,000 downloaders, what is the expected monetary value of downloading the game?

 
## Question 4

A local casino offers a game which costs $2 to play. A fair coin is flipped up to three times, and the payouts work as follows:

- If the coin lands heads on the first toss, you win $2 and the game is over.
- If the coin lands heads on the second toss, you win $4 and the game is over.
- If the coin lands heads on the third toss, you win $8 and the game is over.
- If the coin lands tails all three times, you win $0.

What is the expected monetary value of the game?

## Question 5

Suppose you can bet on either of two dogs: Santaʼs Little Helper or Sheʼs the Fastest. If you bet on Santaʼs Little Helper and he wins, you get $5. If he loses you pay $2. If you bet on Sheʼs the Fastest and she loses, you pay $10. The two dogs have the same chance of winning. How much would a winning bet on Sheʼs the Fastest have to pay for the bets to have the same value? (Assume one or other of the dogs is guaranteed to win).

## Question 6

Suppose Michigan is deciding whether to enact a new tax. If the tax is enacted, it will bring in $700 million in revenue.

But it could also hurt the economy. The chance of harm to the economy is small, just 1/5. But it would cost the country $1,200 million in lost earnings. (The $700 million in revenue would still be gained, partially offsetting this loss.)

Treat gains as positive and losses as negative.

What is the expected monetary value of enacting the new tax?

(Answer in millions of dollars. So if the answer is $700 million, write 700.)

## Question 7 

Extend question 6 in the following way. The government has the option of conducting a study before deciding whether to enact the new tax. If the study’s findings are bad news, that means the chance of harm to the economy is actually double what they thought. If its findings are good news, then the chance of harm to the economy is actually half of what they thought.

Suppose the government conducts the study and its findings are good news. What will the expected monetary value of enacting the tax be then?

(Answer in millions of dollars. So if the answer is $700 million, write 700.)

## Question 8

Suppose the government conducts the study in question 7 and its findings are bad news. What will the expected monetary value of enacting the tax be then?

## Question 9

If the expected monetary value of the tax is what you said in question 6, and the study is bound to deliver good news or bad news, what is the probability of it delivering good news?

## Question 10

Consider the following game: I’m going to flip a fair coin up to three times. If it comes up heads on the first toss, the game is over and you win $2. If it comes up heads for the first time on the second toss, you win $40 and the game is over. If the first heads comes up on the third toss, you win $800 and the game is over. If it comes up tails every time, you have to pay me $x.

What does x have to be to make the game fair?

(Don't worry about the difference between money and utility here - fair just means the expected monetary value of the game is 0)