---
title: "Assignment Week 10"
output:
  pdf_document:
    toc: false
    df_print: kable
    keep_tex: yes
    latex_engine: xelatex
    md_extensions: +fancy_lists
    extra_dependencies: ["gensymb", "nicefrac", "caption", "mathastext"]
    fig_caption: no
fontsize: 11pt
mainfont: SF Pro Text Light
mainfontoptions: "Scale=MatchLowercase"
geometry: margin=1.2in
linestretch: 1.1
author: Philosophy 305
date: Due March 18, 2022, 5pm
---

## Question 1

Youʼre considering downloading a new game for your phone. The game costs $0.99. But as a promotion, the first 50,000 downloaders are being entered in a fair lottery with a $10,000 cash prize. If you know youʼll be one of the first 50,000 downloaders, what is the expected monetary value of downloading the game?

 
## Question 2

A local casino offers a game which costs $2 to play. A fair coin is flipped up to three times, and the payouts work as follows:

- If the coin lands heads on the first toss, you win $2 and the game is over.
- If the coin lands heads on the second toss, you win $4 and the game is over.
- If the coin lands heads on the third toss, you win $8 and the game is over.
- If the coin lands tails all three times, you win $0.

What is the expected monetary value of the game?

## Question 3

Suppose you can bet on either of two dogs: Santaʼs Little Helper or Sheʼs the Fastest. If you bet on Santaʼs Little Helper and he wins, you get $5. If he loses you pay $2. If you bet on Sheʼs the Fastest and she loses, you pay $10. The two dogs have the same chance of winning. How much would a winning bet on Sheʼs the Fastest have to pay for the bets to have the same value? (Assume one or other of the dogs is guaranteed to win).

## Question 4

Suppose Michigan is deciding whether to enact a new tax. If the tax is enacted, it will bring in $700 million in revenue.

But it could also hurt the economy. The chance of harm to the economy is small, just 1/5. But it would cost the country $1,200 million in lost earnings. (The $700 million in revenue would still be gained, partially offsetting this loss.)

Treat gains as positive and losses as negative.

What is the expected monetary value of enacting the new tax?

(Answer in millions of dollars. So if the answer is $700 million, write 700.)

## Question 5 

Extend question 4 in the following way. The government has the option of conducting a study before deciding whether to enact the new tax. If the study’s findings are bad news, that means the chance of harm to the economy is actually double what they thought. If its findings are good news, then the chance of harm to the economy is actually half of what they thought.

Suppose the government conducts the study and its findings are good news. What will the expected monetary value of enacting the tax be then?

(Answer in millions of dollars. So if the answer is $700 million, write 700.)

## Question 6

Suppose the government conducts the study in question 5 and its findings are bad news. What will the expected monetary value of enacting the tax be then?

## Question 7

If the expected monetary value of the tax is what you said in question 6, and the study is bound to deliver good news or bad news, what is the probability of it delivering good news?

## Question 8

Some workplaces hold a weekly lottery. Suppose there are 30 people in your workplace lottery, and each person pays in $5 every Monday. A finalist is chosen at random every Friday, for three weeks. Then, on the fourth Friday, one of the three finalists from the previous three weeks is chosen at random. That person gets all the prize money.

What is the expected value of being in the lottery?

\newpage 

## Question 9

Sonia has tickets to see The Weeknd tomorrow night. Her friend has tickets to see Beyoncé, and also tickets to Katy Perry. Beyoncé is Sonia’s favourite performer, in fact she would rather see Beyoncé than The Weeknd.

Sonia’s friend offers a gamble in exchange for her tickets to The Weeknd. The gamble has a 9/10 chance of winning, in which case Sonia gets the Beyoncé tickets (utility 1). Otherwise she gets the Katy Perry tickets (utility 0).

If Sonia declines the gamble, what can we conclude?

a. For Sonia, the utility of seeing The Weeknd is 9/10
b. For Sonia, the utility of seeing The Weeknd is greater than 9/10
c. For Sonia, the utility of seeing The Weeknd is less than 9/10
d. For Sonia, the utility of seeing The Weeknd is 1/10

 
## Questions 10-12

Eleanor wants to get a job at Google so she's going to university to study computer science. She has to decide between Wayne State and Michigan State. Suppose 1/100 of Wayne State's computer science students get jobs at Google and the rest get jobs at Facebook. For Eleanor, a job at Google has utility 200 while a job at Facebook has utility 50.

12. What is the expected utility of going to Wayne State for Eleanor?

Suppose Michigan State students have better odds of getting a job at Google: 5/400. And 360/400 students go to work at Amazon, which Eleanor would prefer to Facebook. On the other hand, the remaining 35/400 of them don't get a job at all, which has utility zero for Eleanor. After thinking about it, she can't decide: Wayne State and Michigan State seem like equally good options to her.

13. How much utility does working at Amazon have for Eleanor?

Suppose Eleanor ends up going to Wayne State, and now she's about to graduate. Unfortunately, Google isn't hiring any more. The only jobs available are at Amazon and Facebook. She would have to take a special summer training program to qualify for a job at Amazon, though. And that would mean she can't get a job at Facebook. Facebook is offering her a job, but she has to take it now or never. So, she has to either take the guaranteed job at Facebook right now, or gamble on the summer program. The summer program could get her a job at Amazon, or it could leave her unemployed.

14. How high would the probability of getting a job at Amazon have to be for Eleanor to be indifferent between taking and not taking the special summer program?